//Generated by Copilot

const http = require('http');

function fetchData(url, callback) {
  http.get(url, (res) => {
    let data = '';

    // Collect data chunks
    res.on('data', (chunk) => {
      data += chunk;
    });

    // Once all data is collected
    res.on('end', () => {
      callback(null, JSON.parse(data));
    });

  }).on('error', (err) => {
    callback(err, null);
  });
}

function groupByMiner(blocks) {
  const minerCounts = {};

  blocks.forEach((block) => {
    const miner = block.miner;
    if (minerCounts[miner]) {
      minerCounts[miner]++;
    } else {
      minerCounts[miner] = 1;
    }
  });

  return minerCounts;
}

const url = 'http://localhost:5003/blocks';
fetchData(url, (err, blocks) => {
  if (err) {
    console.error('Error fetching data:', err);
    return;
  }

  const minerCounts = groupByMiner(blocks);
  console.log('Miner Counts:', minerCounts);
});
